<?php $post = self::get('post'); ?>
<form method="post" action="<?php _e(actionUrl())?>" onsubmit="return ajax_form(this)">
<input type="hidden" value="<?php _e($post['ID']);?>" name="ID"/>
<div class="x-form-container" style="overflow: true;">
<div class="form-message"></div>
<table width="100%" border="0" cellpadding="5" class="x-form">
	<tr>
		<td class="x-form-label">
			Tên phòng ban:
		</td>
		<td class="x-form-content">
			<input name="title" type="text" style="width:250px;" class="x-text" value="<?php _e($post['title']);?>"/>
		</td>
	</tr>
	<tr>	
		<td class="x-form-label">
			Thứ tự:
		</td>
		<td class="x-form-content">
			<input name="ord" type="text" style="width:30px;" class="x-text" value="<?php _e($post['ord'])?>"/>
		</td>
	</tr>	
	<tr>	
		<td class="x-form-label">
			Trực thuộc:
		</td>
		<td class="x-form-content">
			<select name="parent_id" class="x-select" style="width:258px">
			<option value='0'><?php _e(str_repeat('-', 55)) ?></option>
			<?php _e(select_options(self::get('departments'), 'title', $post['parent_id'])); ?>	
			</select>
		</td>
	</tr>
	<tr>
		<td class="x-form-label" valign="top">
			Mô tả:
		</td>
		<td class="x-form-content">
			<textarea name="desc" style="width:250px" class="x-text" rows="6"><?php _e($post['desc']); ?></textarea>
		</td>
	</tr>
	<tr>
		<td align="center" colspan="2">
			<?php _e(tpl_button_add()) ?>
			<a onclick="remove_frame(this)" class="x-button x-fresh">Hủy bỏ</a>
		</td>
	</tr>
</table>
</div>
</form>