<?php $post = self::get('post'); ?>
<form method="post" action="<?php _e(actionUrl())?>" onsubmit="return ajax_form(this)">
<input type="hidden" value="<?php _e($post['ID']);?>" name="ID"/>
<div class="x-form-container" style="overflow: true;">
<div class="form-message"></div>
<table width="100%" border="0" cellpadding="5" class="x-form">
	<tr>
		<td class="x-form-label">
			Câu hỏi:
		</td>
		<td class="x-form-content">
			<input name="title" type="text" style="width:600px;" class="x-text" value="<?Php _e( $post['title'] ) ?>"/>
		</td>
	</tr>
	<tr>
		<td class="x-form-label">
			Là menu:
		</td>
		<td class="x-form-content">
			<input type="hidden" name="is_menu" value="no"/>
			<input type="checkbox" name="is_menu" value="yes"<?php _e( $post['is_menu']=='yes' ? 'checked': '' );?>/>
		</td>
	</tr>
	<tr>
		<td class="x-form-label">
			Trong mục:
		</td>
		<td class="x-form-content">
			<select name="parent_id" class="x-select" style="width:610px">
			<option value='0'></option>
			<?php _e(select_options(self::get('posts'), 'title', $post['parent_id'], $post['ID'])); ?>
			</select>
		</td>
	</tr>
	<tr>
		<td class="x-form-label">
			Thứ tự:
		</td>
		<td class="x-form-content">
			<input name="ord" type="text" style="width:30px;" class="x-text" value="<?Php _e( $post['ord'] );?>"/>
		</td>
	</tr>
	<tr>
		<td class="x-form-label" valign="top">
			Nội dung:
		</td>
		<td class="x-form-content">
            <?php _e(tpl_editor('content',$post['content']) )?>
        </td>
	</tr>
	<tr>
		<td></td>
		<td>
			<input type="submit" class="x-button x-save" value="Cập nhật"/>
			<a href="#Admin/Faq" class="x-button x-fresh">Hủy bỏ</a>
		</td>
	</tr>
</table>
</div>
</form>