<div class="x-list-title">
    <table width="100%" border="0" height="100%">
        <tr>
            <td align="left"><h2><?php _e(translate('default.admin.hotel.manager')) ?></h2></td>
            <td align="right">
                 <?php
                _e(tpl_search_form(baseUrl() . '/Admin/Hotels?s='.self::get('s'), null, 'Tiêu đề'));
                ?>
                 <a href="#Admin/Hotels/Add" class="x-button x-button-add">Tạo mới</a>
            </td>
        </tr>
    </table>
</div>
<?php
    list($posts, $vars, $page) = self::get(array('posts', 'vars', 'page'));
    $link = '#Admin/Hotels';
    $id = getId();
?>
<form  id="<?php _e($id); ?>" method="post"  onsubmit="return ajax_form(this)" >
<table cellpadding="0" class="x-list" width="100%">
    <?php if ( isset($posts) && count($posts) > 0 ): ?>
        <tr>
            <th class="k"><?php _e(translate('default.list.index')) ?></th>

            <th><?php _e(translate('default.image')) ?></th>

            <th>
                 <?php  show_order_link( translate('default.title'), 'title', $link, $vars ); ?>
            </th>

            <th>
                 <?php  show_order_link( translate('default.is_active'), 'is_active', $link, $vars ); ?>
            </th>
            
            <th>
                 <?php  show_order_link( 'Chủ khách sạn', 'fullname', $link, $vars ); ?>
            </th>



            <th colspan="2" witdh="25"><?php _e(translate('default.list.action')); ?></th>

            <th class="k">
            <div class="x-check-container">
                <div class="x-check">
                    <input rows="tr" type="checkbox" class="x-checkbox"/>
                </div>
                <div class="x-check-options">
                    <div class="s"><span><?php _e(translate('default.action.check')) ?></span></div>
                    <a class="x-check-item" rows="tr">
                        <?php _e(translate('default.action.check_all')) ?>
                    </a>
                    <div class="x-check-actions">
                        <div class="s"><span><?php _e(translate('default.action.dones')) ?></span></div>
                        <a onclick="module_delete('<?php _e(baseUrl()); ?>/<?php _e(self::getModule()) ?>/<?php _e(self::getController()) ?>/Delete','<?php _e($id); ?>',this)" class="x-check-action">
                            <?php _e(translate('default.action.remove')) ?>
                        </a>
                        <a onclick="module_ajax('<?php _e(baseUrl()); ?>/<?php _e(self::getModule()) ?>/<?php _e(self::getController()) ?>/Active','<?php _e($id); ?>',this)" class="x-check-action">
                            <?php _e('Kích hoạt khách sạn đã chọn'); ?>
                        </a>
                        <a onclick="module_ajax('<?php _e(baseUrl()); ?>/<?php _e(self::getModule()) ?>/<?php _e(self::getController()) ?>/Noactive','<?php _e($id); ?>',this)" class="x-check-action">
                            <?php _e('Hủy kích hoạt khách sạn đã chọn'); ?>
                        </a>

                    </div>
                </div>
            </div>
        </th>
    </tr>
    <?php
        foreach ( $posts as $k => $a ):
            $stt    = $k + 1;
            $id     = $a['ID'];
            $title  = $a['title'];
     ?>
        <tr>
            <td align="center" class="k"><?php _e($stt) ?> </td>
             <td align="center" width="200" valign="top">
                <img src="<?php _e(baseUrl()) ?>/files/<?php if ( !$a['img'] ): ?>photo/noavatar.gif<?php else : ?>/hotel/<?php _e($a['img']); ?><?php endif; ?>" style="max-width:100px" class="personnel-photo"/>
                 <div style="padding:3px;font-weight:bold;font-size:12pt"><?php _e($a['code']) ?></div>
            </td>


            <td><a href="#Admin/Hotels/View?ID=<?php _e($id) ?>"><?php _e($title) ?></a></td>

            <td align='center' >
                 <a href="<?php _e(append_url("#Admin/Hotels?is_active={$a['is_active']}", $vars)); ?>">
                    <?php ($a['is_active']== 1)?_e(translate('default.hotel.active')):  _e(translate('default.hotel.noactive')) ?>
                 </a>
            </td>
             <td  align='center'><?php _e($a['fullname']) ?></a></td>
            <td width='30' align='center'>
                 <a href="#Admin/Hotels/Edit?ID=<?php _e($id) ?>" class="x-edit"></a>
	    </td>

            <td class="k" align='center'>
                <a onclick='module_delete("<?php _e(baseUrl()); ?>/Admin/Hotels/Delete?ID[]=<?php _e($id); ?>")' class='x-delete'></a>
            </td>

            <td align="center">
                <input name="ID[]" value="<?php _e($a['ID']) ?>" type="checkbox"/>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
<tr>
    <td colspan="8" class="page">
        <div class="x-page">
            <?php self::e("page"); ?>
        </div>
    </td>
</tr>
</table>

</form>

