<?php $post = self::get('post'); ?>
<form method="post" action="<?php _e(actionUrl())?>" onsubmit="return ajax_form(this)">
<input type="hidden" value="<?php _e($post['ID']);?>" name="ID"/>
<div class="x-form-container" style="overflow: true;">
<div class="form-message"></div>
<table width="100%" border="0" cellpadding="5" class="x-form">
	<tr>
		<td class="x-form-label">
			Tên mục dự án:
		</td>
		<td class="x-form-content">
			<input name="title" type="text" style="width:250px;" class="x-text" value="<?php _e($post['title']);?>"/>
		</td>
	</tr>
	<tr>
		<td align="center" colspan="2">
			<input type="submit" class="x-button x-save" value="Cập nhật"/>
			<a onclick="remove_frame(this)" class="x-button x-fresh">Hủy bỏ</a>
		</td>
	</tr>
</table>
</div>
</form>