<div class="x-list-title">
<table width="100%" border="0" height="100%">
	<tr>
		<td align="left">
		<h2>Quản lý bộ nhớ</h2>
		</td>
		<td align="right"></td>
	</tr>
</table>
</div>
<div class="x-form-container">
<div style="padding: 20px">
<table cellpadding="0">
	<tr>
		<td>
		<button class="x-button" onclick="admin_optermize(this)">Tiến hành
		quét</button>
		</td>
		<td>
		<div
			style="display: inline-block; height: 25px; border: 1px solid #637AAE; background: #fff; width: 300px; position: relative"
			id="optermize-progress">
		<div id="optermize_status"
			style="background: #8CBD57; height: 25px; width: 0%; position: absolute; left: 0px; top: 0px"></div>
		</div>
		</td>
	</tr>
</table>
</div>
</div>
