<div class="x-list-title">
    <table width="100%" border="0" height="100%">
        <tr>
            <td align="left">
                <h2> Danh sách từ khóa	</h2>
            </td>
            <td align="right">
            </td>
        </tr>

    </table>
</div>
<div style="border:1px solid #ccc;padding:10px">
    <div style="border:1px dotted green;padding:10px">
        Bảng tra cứu từ khóa tương ứng các phân hệ được sử dụng trong các file template.
        Ví dụ từ khóa <b>"code"</b> khi sử dụng sẽ được đặt trong file template là <b>"{code}"</b>
    </div>
    <h1>Nhân sự</h1>
    <h2>Hồ sơ nhân sự</h2>
    <table width="500" border="1" cellpadding="5" cellspacing="5">
        <tr>
            <th>Từ khóa</td>
            <th>Mô tả</td>
        </tr>
        <tr>
            <td>code</td>
            <td>Mã nhân viên</td>
        </tr>
        <tr>
            <td>name</td>
            <td>Họ tên nhân viên</td>
        </tr>
        <tr>
            <td>first_name</td>
            <td>Họ nhân viên</td>
        </tr>
        <tr>
            <td>last_name</td>
            <td>Tên nhân viên</td>
        </tr>
        <tr>
            <td>birthday</td>
            <td>Ngày sinh</td>
        </tr>
        <tr>
            <td>place_birthday</td>
            <td>Nơi sinh</td>
        </tr>
        <tr>
            <td>private_code</td>
            <td>CMTND</td>
        </tr>
        <tr>
            <td>private_code_date</td>
            <td>Cấp ngày</td>
        </tr>
        <tr>
            <td>private_code_place</td>
            <td>Nơi cấp</td>
        </tr>
        <tr>
            <td>home_address</td>
            <td>Địa chỉ thường trú</td>
        </tr>
        <tr>
            <td>current_address</td>
            <td>Địa chỉ tạm trú </td>
        </tr>
        <tr>
            <td>job_date_join</td>
            <td>Ngày vào công ty</td>
        </tr>
        <tr>
            <td>position_title</td>
            <td>Chức vụ </td>
        </tr>
        <tr>
            <td>mobile</td>
            <td>Điện thoại </td>
        </tr>
        <tr>
            <td>date_now</td>
            <td>Ngày tháng năm hiện tại</td>
        </tr>
        <tr>
            <td>date_now_day</td>
            <td>Ngày hiện tại</td>
        </tr>
        <tr>
            <td>date_now_month</td>
            <td>Tháng hiện tại</td>
        </tr>
        <tr>
            <td>date_now_year</td>
            <td>Năm hiện tại</td>
        </tr>
        <tr>
            <td>job_date_out</td>
            <td>Ngày tháng năm nghỉ việc</td>
        </tr>
        <tr>
            <td>job_date_out_day</td>
            <td>Ngày nghỉ việc</td>
        </tr>
        <tr>
            <td>job_date_out_month</td>
            <td>Tháng nghỉ việc</td>
        </tr>
        <tr>
            <td>job_date_out_year</td>
            <td>Năm nghỉ việc</td>
        </tr>
         <tr>
            <td>department</td>
            <td>Phòng ban</td>
        </tr>
         <tr>
            <td>staft_job_date_join</td>
            <td>Ngày tháng năm vào</td>
        </tr>
         <tr>
            <td>staft_job_day</td>
            <td>Ngày vào</td>
        </tr>
         <tr>
            <td>staft_job_month</td>
            <td>Tháng vào</td>
        </tr>
         <tr>
            <td>staft_job_year</td>
            <td>Năm vào</td>
        </tr>
    </table>
    <h2>Hợp đồng lao động</h2>
    <table width="500" border="1" cellpadding="5" cellspacing="5">
        <tr>
            <th>Từ khóa</td>
            <th>Mô tả</td>
        </tr>
        <tr>
            <td>code</td>
            <td>Mã hợp đồng</td>
        </tr>
        <tr>
            <td>title</td>
            <td>Tên hợp đồng</td>
        </tr>
        <tr>
            <td>date_reg</td>
            <td>Ngày kí</td>
        </tr>
        <tr>
            <td>staft_name</td>
            <td>Tên nhân viên</td>
        </tr>

        <tr>
            <td>staft_birthday</td>
            <td>Ngày sinh</td>
        </tr><tr>
            <td>staft_place_of_birth</td>
            <td>Nơi sinh</td>
        </tr><tr>
            <td>staft_home_address</td>
            <td>Địa chỉ thường trú</td>
        </tr>
        <tr>
            <td>staft_private_code</td>
            <td>Số CMTND</td>
        </tr><tr>
            <td>staft_private_code_date</td>
            <td>Ngày cấp</td>
        </tr><tr>
            <td>staft_private_code_place</td>
            <td>Nơi cấp</td>
        </tr>
        <tr>
            <td>deadline</td>
            <td>Thời hạn hợp đồng</td>
        </tr>
        <tr>
            <td>department</td>
            <td>Phòng ban</td>
        </tr>
         <tr>
            <td>position_title</td>
            <td>Chức vụ</td>
        </tr>
         <tr>
            <td>staft_job_title</td>
            <td>Chức danh</td>
        </tr>
        <tr>
            <td>staft_representative</td>
            <td>Người đại diện kí</td>
        </tr>
         <tr>
            <td>date_start</td>
            <td>Ngày tháng năm bắt đầu</td>
        </tr>
         <tr>
            <td>date_finish</td>
            <td>Ngày tháng năm kết thúc</td>
        </tr>
        <tr>
            <td>date_start_date_day</td>
            <td>Ngày bắt đầu</td>
        </tr>
        <tr>
            <td>date_start_date_month</td>
            <td>Tháng bắt đầu</td>
        </tr>
        <tr>
            <td>date_start_date_year</td>
            <td>Năm bắt đầu</td>
        </tr>
        <tr>
            <td>job_day_test_one</td>
            <td>Ngày hết thử việc 1 tháng</td>
        </tr>
         <tr>
            <td>job_month_test_one</td>
            <td>Tháng hết thử việc 1 tháng</td>
        </tr>
         <tr>
            <td>job_year_test_one</td>
            <td>Năm hết thử việc 1 tháng</td>
        </tr>
         <tr>
            <td>job_day_test_begin_three</td>
            <td>Ngày bắt đầu thử việc 3 tháng</td>
        </tr>
         <tr>
            <td>job_month_test_begin_three</td>
            <td>Tháng bắt đầu thử việc 3 tháng</td>
        </tr>
         <tr>
            <td>job_year_test_begin_three</td>
            <td>Năm bắt đầu thử việc 3 tháng</td>
        </tr>
         <tr>
            <td>job_day_test_end_three</td>
            <td>Ngày hết thử việc 3 tháng</td>
        </tr>
         <tr>
            <td>job_month_test_end_three</td>
            <td>Tháng hết thử việc 3 tháng</td>
        </tr>
         <tr>
            <td>job_year_test_end_three</td>
            <td>Năm hết thử việc 3 tháng</td>
        </tr>
        
         <tr>
            <td>job_day_begin_one</td>
            <td>Ngày bắt đầu hợp đồng 1 năm lần 1</td>
        </tr>
         <tr>
            <td>job_month_begin_one</td>
            <td>Tháng bắt đầu hợp đồng 1 năm lần 1</td>
        </tr>
         <tr>
            <td>job_year_begin_one</td>
            <td>Năm bắt đầu hợp đồng 1 năm lần 1</td>
        </tr>
         <tr>
            <td>job_day_end_one</td>
            <td>Ngày kết thúc hợp đồng 1 năm lần 1</td>
        </tr>
         <tr>
            <td>job_month_end_one</td>
            <td>Tháng kết thúc hợp đồng 1 năm lần 1</td>
        </tr>
         <tr>
            <td>job_year_end_one</td>
            <td>Năm kết thúc hợp đồng 1 năm lần 1</td>
        </tr>
        
        <tr>
            <td>job_day_begin_two</td>
            <td>Ngày bắt đầu hợp đồng 1 năm lần 2</td>
        </tr>
         <tr>
            <td>job_month_begin_two</td>
            <td>Tháng bắt đầu hợp đồng 1 năm lần 2</td>
        </tr>
         <tr>
            <td>job_year_begin_two</td>
            <td>Năm bắt đầu hợp đồng 1 năm lần 2</td>
        </tr>
         <tr>
            <td>job_day_end_two</td>
            <td>Ngày kết thúc hợp đồng 1 năm lần 2</td>
        </tr>
         <tr>
            <td>job_month_end_two</td>
            <td>Tháng kết thúc hợp đồng 1 năm lần 2</td>
        </tr>
         <tr>
            <td>job_year_end_two</td>
            <td>Năm kết thúc hợp đồng 1 năm lần 2</td>
        </tr>
        
        <tr>
            <td>job_day_limit</td>
            <td>Ngày bắt đầu hợp đồng vô thời hạn</td>
        </tr>
         <tr>
            <td>job_month_limit</td>
            <td>Tháng bắt đầu hợp đồng vô thời hạn</td>
        </tr>
         <tr>
            <td>job_year_limit</td>
            <td>Năm bắt đầu hợp đồng vô thời hạn</td>
        </tr>
        
        
        <tr>
            <td>date_finish_day</td>
            <td>Ngày kết thúc</td>
        </tr>
        <tr>
            <td>date_finish_month</td>
            <td>Tháng kết thúc</td>
        </tr>
        <tr>
            <td>date_finish_year</td>
            <td>Năm kết thúc</td>
        </tr>
        <tr>
            <td>date_now</td>
            <td>Ngày tháng năm hiện tại</td>
        </tr>
        <tr>
            <td>date_now_day</td>
            <td>Ngày hiện tại</td>
        </tr>
        <tr>
            <td>date_now_month</td>
            <td>Tháng hiện tại</td>
        </tr>
        <tr>
            <td>date_now_year</td>
            <td>Năm hiện tại</td>
        </tr>
        <tr>
            <td>salary</td>
            <td>Lương thỏa thuận</td>
        </tr>
         <tr>
            <td>salary_premium</td>
            <td>Lương bảo hiểm</td>
        </tr>
         <tr>
            <td>salary_effective</td>
            <td>Lương hiệu quả</td>
        </tr>


    </table>
    
    <h1>Tài sản</h1>
    <h2>Biên bản bàn giao</h2>
    <table width="500" border="1" cellpadding="5" cellspacing="5">
        <tr>
            <th>Từ khóa</td>
            <th>Mô tả</td>
        </tr>
        <tr>
            <td>code</td>
            <td>Mã nhân viên</td>
        </tr>
        <tr>
            <td>name</td>
            <td>Họ tên nhân viên</td>
        </tr>
        <tr>
            <td>birthday</td>
            <td>Ngày sinh</td>
        </tr>
        <tr>
            <td>place_birthday</td>
            <td>Nơi sinh</td>
        </tr>
        <tr>
            <td>private_code</td>
            <td>CMTND</td>
        </tr>
        <tr>
            <td>private_code_date</td>
            <td>Cấp ngày</td>
        </tr>
        <tr>
            <td>private_code_place</td>
            <td>Nơi cấp</td>
        </tr>
        <tr>
            <td>position_title</td>
            <td>Chức vụ </td>
        </tr>
        <tr>
            <td>department</td>
            <td>Phòng ban</td>
        </tr>
        <tr>
            <td>mobile</td>
            <td>Điện thoại </td>
        </tr>
        <tr>
            <td>date_now</td>
            <td>Ngày tháng năm hiện tại</td>
        </tr>
        <tr>
            <td>date_now_day</td>
            <td>Ngày hiện tại</td>
        </tr>
        <tr>
            <td>date_now_month</td>
            <td>Tháng hiện tại</td>
        </tr>
        <tr>
            <td>date_now_year</td>
            <td>Năm hiện tại</td>
        </tr>
        <tr>
            <td>staft_job_date_join</td>
            <td>Ngày tháng năm vào</td>
        </tr>
         <tr>
            <td>staft_job_day</td>
            <td>Ngày vào</td>
        </tr>
         <tr>
            <td>staft_job_month</td>
            <td>Tháng vào</td>
        </tr>
         <tr>
            <td>staft_job_year</td>
            <td>Năm vào</td>
        </tr>
        <tr>
            <td>index</td>
            <td>Số thứ tự</td>
        </tr>
        <tr>
            <td>title</td>
            <td>Tên thiết bị</td>
        </tr>
        <tr>
            <td>model</td>
            <td>Serial NO</td>
        </tr>
        <tr>
            <td>price</td>
            <td>Trị giá</td>
        </tr>
        <tr>
            <td>use_status_title</td>
            <td>Tình trạng</td>
        </tr>
        <tr>
            <td>name_deposits</td>
            <td>Đặt cọc</td>
        </tr>
    </table>
</div>