<?php $post = self::get('post'); ?>
<form method="post" action="<?php _e(actionUrl()) ?>" onsubmit="return ajax_form(this)">
    <input type="hidden" name="ID" value="<?php _e($post['ID']) ?>" />
    <div class="x-list-title">
        <table width="100%" border="0" cellpadding="0">
            <tr>
                <td>
                    <h2><?php _e(translate('personnel.import.title')) ?></h2>
                </td>
            </tr>
        </table>
    </div>
    <div class="x-form-container">
        <div class="desc" style="">
            Gửi lại mật khẩu cho các thành viên chưa đăng nhập qua email
        </div>
        <table width="100%" border="0" cellpadding="5" class="x-form">
            <tr>
                <td class="x-form-label" width="220">
                    Người dùng:
                </td>
                <td class="x-form-input">
                    <div class="users">
                        <?php _e(tpl_select_users('user_id[]')); ?>
                    </div><br/>
                    <?php _e(tpl_checkbox('select_user', '1', null, null, 'Tùy chọn người dùng', ' _related="user_id" _related_selector=".users"'));?>
                </td>
            </tr>
            <tr>
                <td class="x-form-label" width="220">
                    Nội dung email:
                </td>
                <td class="x-form-input">
                    <?php _e(tpl_textarea('email_content', self::get('email_content'))) ?>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <div>
                        <h4>Tùy biến:</h4>
                        <ul>
                            <li>{username}: Tên đăng nhập</li>
                            <li>{password}: Mật khẩu</li>
                            <li>{url}: Đường dẫn office</li>
                        </ul>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="x-form-label"></td>
                <td class="x-form-input">
                    <?php _e(tpl_button_add()); ?>
                    <?php _e(tpl_button_cancel('#Admin/User')); ?>
                </td>
            </tr>
        </table>
    </div>
</form>
