<form method="post" action="<?php _e(actionUrl())?>" onsubmit="return ajax_form(this)" id="task-form" enctype="multipart/form-data">
<div class="x-form-container x-form-lightbox">
<div class="form-message"><?php self::e('message'); ?></div>
<table border="0" cellpadding="0" class="x-form">
<tr>
	<td class="x-form-label">
		Mật khẩu cũ: 
	</td>
	<td class="x-form-input">
		<input type="password" name="old_password" style="width:200px" class="x-text" value=""/>
	</td>
</tr>
<tr>
	<td class="x-form-label">
		Mật khẩu mới: 
	</td>
	<td class="x-form-input">
		<input type="password" name="password" style="width:200px" class="x-text" value=""/>
	</td>
</tr>
<tr>	
	<td class="x-form-label">
		Xác nhận lại: 
	</td>
	<td class="x-form-input">
		<input type="password" name="re_password" style="width:200px" class="x-text" value="<?php _e($post['title']);?>"/>
	</td>
</tr>
<tr>
	<td align="center" colspan="2">
		<button type="submit" class="x-button x-save">Đổi mật khẩu</button>
	</td>
</tr>
</table></div>
</form>