<?php
$post = self::get('post');
?>
<form method="post" action="<?php _e(actionUrl()) ?>" onsubmit="return ajax_form(this)">
    <div class="x-form-container" style="overflow: true;">
        <input type="hidden" value="<?php _e($post['ID']); ?>" name="ID"/>
        <div class="form-message"></div>
        <table width="100%" border="0" cellpadding="5" class="x-form">    
            <tr>
                <td class="x-form-label">Ngày :</td>
                <td class="x-form-content">
                    <?php _e(show_date($post['date'])) ?>
                    <input type="hidden" name="date" value="<?php _e($post['date']) ?>" />
                </td>
            </tr>
            <tr>
                <td class="x-form-label">Loại phòng :</td>
                <td class="x-form-content">
                    <?php _e($post['room_type_title']) ?>
                    <input type="hidden" name="room_type_id" value="<?php _e($post['room_type_id']) ?>" />
                    <!-- <?php _e(tpl_select('room_type_id', 'ID', 'title', self::get('room_types'), $post['room_type_id'])) ?> -->
                </td>
            </tr>
            <tr>
                <td class="x-form-label">Đối tác :</td>
                <td class="x-form-content">
                    <?php _e(tpl_select('partner_id', 'ID', 'title', self::get('partners'), $post['partner_id'])) ?>
                </td>
            </tr>
            <tr>
                <td class="x-form-label">Giá trị :</td>
                <td class="x-form-content">
                    <?php _e(tpl_input_number('number',$post['number'])) ?>
                </td>
            </tr>
            <tr>	
                <td class="x-form-label" valign="top"><?php _e(translate('default.desc') . ':') ?></td>
                <td class="x-form-content">
                    <textarea name="desc" style="width:250px" class="x-text" rows="6"><?php _e($post['desc']); ?></textarea>
                </td>
            </tr>        
            <tr>
                <td align="center" colspan="2">
                    <?php _e(tpl_button_add()) ?>
                    <a onclick="remove_frame(this)" class="x-button x-fresh">Hủy bỏ</a>
                </td>
            </tr>
        </table>
    </div>
</form>