<?php
list($posts, $vars, $page) = self::get(array('posts', 'vars', 'page'));
$id = getId();
?>
<div class="x-list-title">
    <table width="100%" border="0" height="100%">
        <tr>
            <td align="left"><h2>Danh sách Commission</h2></td>
            <td align="right">
                <?php
                _e(tpl_search_form(baseUrl() . '/Hotel/Partners/Index?s=' . self::get('s'), null, 'Tên đối tác'));
                ?>   
                <a href="#Hotel/Commission/Add" class="x-button x-button-add">Tạo mới</a>                                
            </td>
        </tr>
    </table>
</div>

<form  id="<?php _e($id); ?>" method="post"  onsubmit="return ajax_form(this)" >
    <table cellpadding="0" class="x-list" width="100%">
        <?php if (isset($posts) && count($posts) > 0): ?>
            <tr>
                <th class="k"><?php _e(translate('default.list.index')) ?></th>

                <th><?php show_order_link('Đối tác', 'title', $link, $vars) ?></th>
                
                <th><?php show_order_link('Hoa hồng', 'title', $link, $vars) ?></th>
                
                <th><?php show_order_link('Khách sạn', 'title', $link, $vars) ?></th>                                
                
                <th><?php show_order_link('Ngày bắt đầu', 'title', $link, $vars) ?></th>
                
                <th><?php show_order_link('Ngày kết thúc', 'title', $link, $vars) ?></th>

                <th><?php show_order_link('Mô tả', 'desc', $link, $vars)?></th> 
                
                <th colspan="2"><?php _e('Tác vụ') ?></th>
                <th class="k">
            <div class="x-check-container">
                <div class="x-check">
                    <input rows="tr" type="checkbox" class="x-checkbox"/>
                </div>
                <div class="x-check-options">
                    <div class="s"><span><?php _e(translate('default.action.check')) ?></span></div>
                    <a class="x-check-item" rows="tr">
                        <?php _e(translate('default.action.check_all')) ?>
                    </a>
                    <div class="x-check-actions">
                        <div class="s"><span><?php _e(translate('default.action.dones')) ?></span></div>
                        <a onclick="module_delete('<?php _e(baseUrl()); ?>/<?php _e(self::getModule()) ?>/<?php _e(self::getController()) ?>/Delete','<?php _e($id); ?>',this)" class="x-check-action">
                            <?php _e(translate('default.action.remove')) ?>
                        </a>

                    </div>
                </div>
            </div>
            </th>
            </tr>
            <?php
            $stt = 0;
            foreach ($posts as $k => $a): 
                ?>
                <tr>
                    <td align="center" class="k"><?php _e($k + 1) ?> </td>
                    <td align="center">   
                        <a href="<?php _e(append_url("#Hotel/Commission?partner_id={$a['partner_id']}", $vars)); ?>">
                            <?php _e($a['partner_name']) ?>
                        </a>
                    </td>

                    <td align='center' >
                        <?php _e($a['percent'].' %') ?>
                    </td>
                    
                    <td align='center' >
                        <?php _e($a['hotel_name']) ?>
                    </td>           
                    
                    <td align='center' >
                        <?php _e(date('d/m/Y', strtotime($a['date_start']))) ?>
                    </td>                        

                    <td align='center' >
                        <?php _e(date('d/m/Y', strtotime($a['date_end']))) ?>
                    </td>                        
                    
                    <td align='center' >
                        <?php _e($a['desc']) ?>
                    </td>                        
                    
                    <td align="center">
                        <a href="#Hotel/Commission/Edit?ID=<?php _e($a['ID']) ?>" class="x-edit"></a>
                    </td>

                    <td class="k" align='center'>
                        <a onclick='module_delete("<?php _e(baseUrl()); ?>/Hotel/Commission/Delete?ID[]=<?php _e($a['ID']); ?>")' class='x-delete'></a>
                    </td>

                    <td align="center">
                        <input name="ID[]" value="<?php _e($a['ID']) ?>" type="checkbox"/>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        <tr>
            <td></td>
            <td colspan="8" class="page">
                <div class="x-page">
                    <?php _e($page); ?>
                </div>
            </td>
        </tr>
    </table>

</form>


