<?php
list($posts, $vars, $page) = self::get(array('posts', 'vars', 'page'));
$link = '#Hotel/Feedback';
$id = getId();

$date_from = self::get('date_from');
$date_to = self::get('date_to');
$id1 = getId();
$id2 = getId();

$a = to_query_configs($vars);
?>

<div class="x-list-title">
    <table width="100%" border="0" height="100%">
        <tr>
            <td align="left"><h2><?php _e('Danh sách phản hồi khách hàng') ?></h2></td>
            <td>
                Từ ngày
                <input id="<?php _e($id1) ?>" type="text" name="date" value="<?php _e($date_from) ?>" style="padding-top:5px;padding-bottom:5px" onclick="date_picker(this,{format: 'd/m/Y',onChange: function(){ location.hash = '<?php _e($link) ?>?date_from='+this.value +'&date_to='+$('#<?php _e($id2) ?>').get('value') ; } })" class="x-text x-date" autocomplete="off">
                đến <input id="<?php _e($id2) ?>" type="text" name="date" value="<?php _e($date_to) ?>" style="padding-top:5px;padding-bottom:5px" onclick="date_picker(this,{format: 'd/m/Y',onChange: function(){ location.hash = '<?php _e($link) ?>?date_from='+$('#<?php _e($id1) ?>').get('value')+'&date_to='+this.value ; } })" class="x-text x-date" autocomplete="off">                                                    
            </td>
            <td align="right">
                <?php
                _e(tpl_search_form(baseUrl() . '/Hotel/Feedback?date_from=' .  $date_from . '&date_to=' . $date_to.'&s='.self::get('s'), null, 'Tiêu đề'));
                ?>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <?php
                _e(tpl_button_options('Xuất file', array(
                            array('Excel 2003', baseUrl() . '/Hotel/Feedback?' . $a . '&export=Excel2003'),
                            array('Excel 2007', baseUrl() . '/Hotel/Feedback?' . $a . '&export=Excel2007')
                        )));
                ?>                
            </td>
        </tr>
    </table>
</div>

<form  id="<?php _e($id); ?>" method="post"  onsubmit="return ajax_form(this)" >
    <table cellpadding="0" class="x-list" width="100%">
        <?php if (isset($posts) && count($posts) > 0): ?>
            <tr>
                <th class="k"><?php _e(translate('default.list.index')) ?></th>

                <th><?php show_order_link('Khách sạn', 'hotel_name', $link, $vars) ?></th>

                <th>
                    <?php show_order_link('Khách hàng', 'fullname', $link, $vars) ?>
                </th>
                <th width="30%">
                    <?php show_order_link('Nội dung phản hồi', 'comment', $link, $vars) ?>
                </th>                

                <th >
                    <?php show_order_link('Thời gian', 'time', $link, $vars) ?>
                </th>
                <th><?php _e('Trạng thái') ?></th>
                <th colspan="2"><?php _e('Tác vụ') ?></th>
                <th class="k">
            <div class="x-check-container">
                <div class="x-check">
                    <input rows="tr" type="checkbox" class="x-checkbox"/>
                </div>
                <div class="x-check-options">
                    <div class="s"><span><?php _e(translate('default.action.check')) ?></span></div>
                    <a class="x-check-item" rows="tr">
                        <?php _e(translate('default.action.check_all')) ?>
                    </a>
                    <div class="x-check-actions">
                        <div class="s"><span><?php _e(translate('default.action.dones')) ?></span></div>
                        <a onclick="module_delete('<?php _e(baseUrl()); ?>/<?php _e(self::getModule()) ?>/<?php _e(self::getController()) ?>/Delete','<?php _e($id); ?>',this)" class="x-check-action">
                            <?php _e(translate('default.action.remove')) ?>
                        </a>

                    </div>
                </div>
            </div>
            </th>
            </tr>
            <?php
            $stt = 0;
            foreach ($posts as $k => $a):                
                ?>
            <?php if($a['customer_id'] <> 0) : 
                $stt = $stt + 1;
            ?>
                <tr>
                    <td align="center" class="k"><?php _e($stt) ?> </td>
                    <td align="center">   
                        <?php _e($a['hotel_name']) ?>
                    </td>

                    <td align='center' >
                        <a href="<?php _e($link) ?>?date_from=<?php _e($date_from) ?>&date_to=<?php _e($date_to) ?>&customer_id=<?php _e($a['customer_id']) ?>"><?php _e($a['fullname']) ?></a>
                    </td>

                    <td align='center' width="30%">
                        <?php _e($a['comment']) ?>
                    </td>

                    <td align='center'>
                        <?php _e(date('d/m/Y H:i:s', strtotime($a['time']))) ?>
                    </td>

                    <td align='center'>
                        <a href="<?php _e($link) ?>?date_from=<?php _e($date_from) ?>&date_to=<?php _e($date_to) ?>&status=<?php _e($a['status']) ?>">
                            <?php _e(($a['status'] == 0) ? 'Chưa trả lời' : 'Đã trả lời') ?>
                        </a>
                    </td>

                    <td align="center">
                        <a onclick="load_inframe('<?php _e(baseUrl()); ?>/Hotel/Feedback/Edit?ID=<?php _e($a['ID']) ?>',{title: 'Sửa Feedback', auto_hidden: true })" class="x-edit"></a>
                    </td>

                    <td class="k" align='center'>
                        <a onclick='module_delete("<?php _e(baseUrl()); ?>/Hotel/Feedback/Delete?ID[]=<?php _e($a['ID']); ?>")' class='x-delete'></a>
                    </td>

                    <td align="center">
                        <input name="ID[]" value="<?php _e($a['ID']) ?>" type="checkbox"/>
                    </td>
                </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        <tr>
            <td></td>
            <td colspan="8" class="page">
                <div class="x-page">
                    <?php _e($page); ?>
                </div>
            </td>
        </tr>
    </table>

</form>

