<?php
$post = self::get('post');
$type_id = self::get('type_id');
$colum = 4;
$activity_types = self::get('activity_types');
$facility_types = self::get('facility_types');
$service_types = self::get('service_types');

$currencies = self::get('currencies');

//$airport_currency_id = self::get('airport_transfer_fee_currency_id');
//$breakfast_currency_id = self::get('breakfast_charge_currency_id');
//$internet_currency_id = self::get('internet_usage_currency_id');
//$parking_currency_id = self::get('parking_fee_currency_id');
?>
<div class="x-list-title">
    <table width="100%" border="0" height="100%">
        <tr>
            <td align="left">
                <h2><?php _e(translate("default.hotel.edit.hotel")) ?></h2>
            </td>
            <td align="right">
                <div class="x-list-options">

                </div>
            </td>
        </tr>
    </table>
</div>
<form  method="post" action="<?php _e(actionUrl()) ?>" onsubmit="return ajax_form(this)">
    <input type="hidden" name="ID" value="<?php _e(self::get('ID', getInt('ID'))); ?>"/>
    <div class="tab-container" style="overflow: true;margin-top:-2px">
        <div class="tab-bar">
            <a class="tab-link tab-link-first<?php if (!in_array(get('tab', ''), array('info-hotel', 'info-common', 'images'))) _e(' tab-link-active'); ?>" onclick="do_tab(this,1)"><?php _e('Thông tin chung') ?></a>

            <a class="tab-link<?php if (get('tab', '') == 'info-common') _e(' tab-link-active'); ?>" onclick="do_tab(this,2)"><?php _e('Bổ sung') ?></a>

            <a class="tab-link<?php if (get('tab', '') == 'images') _e(' tab-link-active'); ?>" onclick="do_tab(this,3)"><?php _e('Hình ảnh') ?></a>            

            <span class="clear"></span>
        </div>   
        <div class="form-message"></div>        
        <div class="form-message"></div>
        <div class="tabs">

            <!-- GENERAL -->
            <div class="tab tab-active" >
                <div class="x-form-container">
                    <table width="100%" cellpadding="4" class="x-form">
                        <tr>
                            <td class="c1">
                                <?php _e(translate('default.hotel.field.title')); ?>:
                            </td>
                            <td class="c2">
                                <input type="text" value="<?php _e($post['title'])?>" name="title" class="x-text x-normal-text bor"/>
                            </td>

                            <td class="c1">
                                <?php _e(translate('default.hotel.field.type_id')); ?>:
                            </td>
                            <td class="c2">
                                <select name="type_id" class="x-select" style="width:258px">                   
                                    <?php _e(select_options($type_id, 'title', $post['type_id'])); ?>	
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="c1">
                                <?php _e(translate('default.hotel.field.start')); ?>:
                            </td>
                            <td class="c2">
                                <select name="star" class="x-select">
                                    <option value="0" <?php $post['star'] == '0' ? _e('selected="selected"') : "" ?>></option>
                                    <option value="1" <?php $post['star'] == '1' ? _e('selected="selected"') : "" ?>>1 sao</option>
                                    <option value="2" <?php $post['star'] == '2' ? _e('selected="selected"') : "" ?>>2 sao</option>
                                    <option value="3" <?php $post['star'] == '3' ? _e('selected="selected"') : "" ?>>3 sao</option>
                                    <option value="4" <?php $post['star'] == '4' ? _e('selected="selected"') : "" ?>>4 sao</option>
                                    <option value="5" <?php $post['star'] == '5' ? _e('selected="selected"') : "" ?>>5 sao</option>
                                </select>
                            </td>

                            <td class="c1">
                                <?php _e(translate('default.hotel.field.phone')); ?>:
                            </td>
                            <td class="c2">
                                <input type="text" value="<?php _e(self::get('phone', $post['phone']))?>" name="phone" class="x-text x-normal-text bor"/>
                                
                            </td>

                        </tr>

                        <tr>
                            <td class="c1">
                                <?php _e(translate('default.hotel.field.phone1')); ?>:
                            </td>
                            <td class="c2">
                                <input type="text" value="<?php _e(self::get('phone1', $post['phone1']))?>" name="phone1" class="x-text x-normal-text bor"/>
                            </td>
                            <td class="c1">
                                <?php _e(translate('default.hotel.field.phone2')); ?>:
                            </td>
                            <td class="c2">
                                <input type="text" value="<?php _e(self::get('phone2', $post['phone2']))?>" name="phone2" class="x-text x-normal-text bor"/>
                            </td>
                        </tr>

                        <tr>
                            <td class="c1">
                                <?php _e(translate('default.hotel.field.email')); ?>:
                            </td>
                            <td class="c2">
                                <input type="text" value="<?php _e($post['email'])?>" name="email" class="x-text x-normal-text bor"/>
                            </td>

                            <td class="c1">
                                <?php _e(translate('default.hotel.field.address')); ?>:
                            </td>
                            <td class="c2">
                                <input type="text" value="<?php _e($post['address'])?>" name="address" class="x-text x-normal-text bor"/>
                            </td>
                        </tr>
                        <tr>
                            <td class="c1">
                              Khu vực :
                            </td>

                           <td class="x-form-input">
                                <div>
                                    <select name="country_id" style="min-width:280px" class="x-select" onchange="hotel_load_state(this)">
                                        <option style="color:#ccc">Quốc gia</option>
                                        <?php _e(select_options(Plugins::getCountries(), 'title', isset($post['country_id']) ? $post['country_id'] : 0 )); ?>
                                    </select><br/>				

                                    <select dt="state"  onchange="hotel_load_district(this)" style="min-width:280px" name="state_id" class="x-select">
                                        <option>Tỉnh thành</option>
                                        <?php foreach ((array) self::get('states') as $a): ?>
                                            <option value="<?php _e($a['ID']); ?>"<?php if ($post['state_id'] == $a['ID']) _e(' selected') ?>><?php _e($a['title']); ?></option>
                                        <?php endforeach; ?>						
                                    </select><br/>
                                    <select dt="district" style="min-width:280px" name="district_id" class="x-select">
                                        <option>Quận huyện</option>
                                        <?php foreach ((array) self::get('districts') as $a): ?>
                                            <option value="<?php _e($a['ID']); ?>"<?php if ($post['district_id'] == $a['ID']) _e(' selected') ?>><?php _e($a['title']); ?></option>
                                        <?php endforeach; ?>						
                                    </select>
                                    <br/>
                                </div>
                            </td>      
                            
                        </tr>
                        <tr>
                            <td class="c1">
                                <?php _e(translate('default.hotel.field.website')); ?>:
                            </td>
                            <td class="c2">
                                <input type="text" value="<?php _e($post['website'])?>" name="website" class="x-text x-normal-text bor"/>
                            </td>
                            <td class="c1">
                                <?php _e(translate('default.hotel.field.fax')); ?>:
                            </td>
                            <td class="c2">
                                <input type="text" value="<?php _e($post['fax'])?>" name="fax" class="x-text x-normal-text bor"/>
                            </td>
                        </tr>
                        <tr>
                            <td class="c1">
                                <?php _e(translate('default.hotel.field.checkin_time')); ?>:
                            </td>
                            <td class="c2">
                                <?php _e(tpl_input_time('checkin_time', date('H:i', strtotime($post['checkin_time'])))); ?>
                            </td>
                            <td class="c1">
                                <?php _e(translate('default.hotel.field.checkout_time')); ?>:
                            </td>
                            <td class="c2">
                                <?php _e(tpl_input_time('checkout_time', date('H:i', strtotime($post['checkout_time'])))); ?>
                            </td>

                        </tr>


                        <tr>

                            <td class="c1">
                                <?php _e(translate('default.hotel.field.floor')); ?>:
                            </td>
                            <td class="c2">
                                <?php _e(tpl_input_number('floor', $post['floor'])) ?>
                            </td>

                            <td class="c1">
                                <?php _e(translate('default.hotel.field.status')); ?>:
                            </td>
                            <td class="c2">
                                <?php ($post['is_active'] == 0) ? _e(translate('default.hotel.noactive')) : _e(translate('default.hotel.active')) ?>
                            </td>

                        </tr>

                        <tr>
                            <td class="c1">
                                <?php _e(translate('default.desc')); ?>:
                            </td>
                            <td class="c2">
                                <textarea name="desc" style="width:250px" class="x-text bor" rows="6"><?php _e($post['desc']) ?></textarea>
                            </td>

                            <td class="c1">
                                <?php _e(translate('default.image')); ?>:
                            </td>
                            <td class="x-form-input">
                                <?php if ($post['img']): ?>
                                    <img  src="<?php _e(baseUrl()) ?>/files/hotel/<?php _e($post['img']) ?>" style="max-width:150px"/>
                                <?php endif; ?>
                                <?php _e(tpl_upload('img', 'hotel')) ?>  
                            </td>


                        </tr>

                        <tr>
                            <td class="c1">Bản đồ :</td>
                            <td class="c2">
                                <table>
                                    <tr>
                                        <td>
                                            <table>
                                                <tr>
                                                    <td>
                                                        <p align="left">
                                                        <table  bgcolor="#FFFFCC" width="300">
                                                            <tr>
                                                                <td><b>Kinh độ</b></td>
                                                                <td><b>Vĩ độ</b></td>
                                                                <td></td>
                                                            </tr>
                                                            <tr>
                                                                <td id="lat"></td>
                                                                <td id="lng"></td>
                                                                <td>
                                                                    <input type="button" name="refresh_toado" value="Refresh" />
                                                                </td>
                                                            </tr>
                                                        </table>
                                                        </p>
                                                        <div align="center" id="map" style="width: 400px; height: 300px"><br/>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>

                                </table>
                            </td>
                        </tr>

                        <!-- ACTIVITIES -->
                        <tr>
                            <td colspan="4" class="section">
                                <?php _e(translate("default.hotel.activities")) ?>
                            </td>
                        </tr>
                        <tr width="100%">
                            <td colspan="4">
                                <table width="100%">
                                    <?php
                                    $row_activities = ceil(count(self::get('activity_types')) / $colum);
                                    for ($i = 0; $i < $row_activities; $i++):
                                        ?>
                                        <tr width="100%">
                                            <?php
                                            for ($j = 0; $j < $colum; $j++):
                                                $a = $activity_types[$i * $colum + $j];
                                                ?>
                                                <td valign="top" width="<?php _e(ceil(100 / $colum)) ?>%"  >
                                                    <?php if (isset($a['ID'])): ?>
                                                        <input type="checkbox" name="activities[]" value="<?php _e($a['ID']) ?>"<?php _e($a['checked']); ?>/>
                                                        <?php _e($a['title']); ?>
                                                    <?php endif; ?>
                                                </td>

                                            <?php endfor; ?>
                                        </tr>
                                    <?php endfor; ?> 
                                </table>
                            </td>
                        </tr>
                        <!-- FACILITIES -->
                        <tr>
                            <td colspan="4" class="section">
                                <?php _e(translate("default.hotel.facilities")) ?>
                            </td>
                        </tr>
                        <tr width="100%">
                            <td colspan="4">
                                <table width="100%">
                                    <?php
                                    $row_facilities = ceil(count($facility_types) / $colum);
                                    for ($i = 0; $i < $row_facilities; $i++):
                                        ?>
                                        <tr width="100%">
                                            <?php
                                            for ($j = 0; $j < $colum; $j++):
                                                $a = $facility_types[$i * $colum + $j];
                                                ?>
                                                <td valign="top" width="<?php _e(ceil(100 / $colum)) ?>%"  >
                                                    <?php if (isset($a['ID'])): ?>
                                                        <input type="checkbox" name="facilities[]" value="<?php _e($a['ID']) ?>"<?php _e($a['checked']); ?>/>
                                                        <?php _e($a['title']); ?>
                                                    <?php endif; ?>
                                                </td>

                                            <?php endfor; ?>
                                        </tr>
                                    <?php endfor; ?> 
                                </table>
                            </td>
                        </tr>
                        <!-- SERVICES -->
                        <tr>
                            <td colspan="4" class="section">
                                <?php _e(translate("default.hotel.services")) ?>
                            </td>
                        </tr>
                        <tr width="100%">
                            <td colspan="4">
                                <table width="100%">
                                    <?php
                                    $row_services = ceil(count($service_types) / $colum);
                                    for ($i = 0; $i < $row_services; $i++):
                                        ?>
                                        <tr width="100%">
                                            <?php
                                            for ($j = 0; $j < $colum; $j++):
                                                $a = $service_types[$i * $colum + $j];
                                                ?>
                                                <td valign="top" width="<?php _e(ceil(100 / $colum)) ?>%"  >
                                                    <?php if (isset($a['ID'])): ?>
                                                        <input type="checkbox" name="services[]" value="<?php _e($a['ID']) ?>"<?php _e($a['checked']); ?>/>
                                                        <?php _e($a['title']); ?>
                                                    <?php endif; ?>
                                                </td>

                                            <?php endfor; ?>
                                        </tr>
                                    <?php endfor; ?> 
                                </table>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <!-- COMMON INFOMATION -->
            <div class="tab<?php if (get('tab', '') == 'info-common') _e(' tab-active'); ?>" style="min-height:200px">
                <div class="x-form-container">
                    <table width="100%" cellpadding="4" class="x-form">  
                        <tr>
                            <td><?php _e('Có đưa đón sân bay') ?></td>

                            <td>
                                <input type="radio" name='airport_transfer' value="1" <?php _e($post['airport_transfer'] == 1 ? 'checked=checked' : '') ?>">
                                <?php _e('Có') ?>  
                                &nbsp; &nbsp;<input type="radio" name='airport_transfer' value="0" <?php _e($post['airport_transfer'] == 0 ? 'checked=checked' : '') ?>">
                                <?php _e('Không') ?>                                     
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Phí đưa đón sân bay') ?></td>

                            <td align="left">
                                <?php _e(tpl_input_number('airport_transfer_fee', $post['airport_transfer_fee'])) ?>                                
                                <select name="airport_transfer_fee_currency_id" id="" class="bor">
                                    <?php foreach ($currencies as $a): ?>
                                        <option value="<?php _e($a['ID']) ?>" <?php (_e($post['airport_transfer_fee_currency_id'] == $a['ID'] ? 'selected' : '')) ?>>
                                            <?php _e($a['title']) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Phí ăn sáng') ?></td>

                            <td>
                                <?php _e(tpl_input_number('breakfast_charge', $post['breakfast_charge'])) ?>                                                                
                                <select name="breakfast_charge_currency_id" id="" class="bor">
                                    <?php foreach ($currencies as $a): ?>
                                        <option value="<?php _e($a['ID']) ?>" <?php (_e($post['breakfast_charge_currency_id'] == $a['ID'] ? 'selected' : '')) ?>>
                                            <?php _e($a['title']) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>                                
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Trả phòng') ?></td>

                            <td><?php _e(tpl_input_time('check_out', date('H:i', strtotime($post['check_out'])))); ?></td>

                        </tr>
                        <tr>
                            <td><?php _e('Khoảng cách từ trung tâm thành phố') ?></td>

                            <td><?php _e(tpl_input_number('distance_from_city_center', $post['distance_from_city_center'])) ?> KM</td>
                        </tr>
                        <tr>
                            <td><?php _e('Khoảng cách tới sân bay') ?></td>

                            <td><?php _e(tpl_input_number('distance_to_airport', $post['distance_to_airport'])) ?> KM</td>
                        </tr>
                        <tr>
                            <td><?php _e('Thời gian nhận phòng sớm nhất') ?></td>

                            <td><?php _e(tpl_input_time('earliest_check_in', date('H:i', strtotime($post['earliest_check_in'])))); ?><td>
                        </tr>
                        <tr>
                            <td><?php _e('Thang máy') ?></td>

                            <td>
                                <input type="radio" name='elevator' value="1" <?php _e($post['elevator'] == 1 ? 'checked=checked' : '') ?>">
                                <?php _e('Có') ?>  
                                &nbsp; &nbsp;<input type="radio" name='elevator' value="0" <?php _e($post['elevator'] == 0 ? 'checked=checked' : '') ?>">
                                <?php _e('Không') ?>                                                                     
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Phí sử dụng Internet') ?></td>

                            <td>
                                <?php _e(tpl_input_number('internet_usage_fee', $post['internet_usage_fee'])) ?>                                                                
                                <select name="internet_usage_currency_id" id="" class="bor">
                                    <?php foreach ($currencies as $a): ?>
                                        <option value="<?php _e($a['ID']) ?>" <?php (_e($post['internet_usage_currency_id'] == $a['ID'] ? 'selected' : '')) ?>>
                                            <?php _e($a['title']) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>                                   
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Phòng/Tầng không hút thuốc') ?></td>

                            <td>
                                <input type="radio" name='non_smoking' value="1" <?php _e($post['non_smoking'] == 1 ? 'checked=checked' : '') ?>">
                                <?php _e('Có') ?>  
                                &nbsp; &nbsp;<input type="radio" name='non_smoking' value="0" <?php _e($post['non_smoking'] == 0 ? 'checked=checked' : '') ?>">
                                <?php _e('Không') ?>                                
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Số quầy bar') ?></td>

                            <td>
                                <?php _e(tpl_input_number('number_of_bars', $post['number_of_bars'])) ?>                                                       
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Số lượng nhà hàng') ?></td>

                            <td>
                                <?php _e(tpl_input_number('number_of_restaurants', $post['number_of_restaurants'])) ?>                                                       
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Số lượng phòng') ?></td>

                            <td>
                                <?php _e(tpl_input_number('number_of_rooms', $post['number_of_rooms'])) ?>                                                       
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Có chỗ đậu xe') ?></td>

                            <td>
                                <input type="radio" name='parking' value="1" <?php _e($post['parking'] == 1 ? 'checked=checked' : '') ?>">
                                <?php _e('Có') ?>  
                                &nbsp; &nbsp;<input type="radio" name='parking' value="0" <?php _e($post['parking'] == 0 ? 'checked=checked' : '') ?>"><?php _e('Không') ?>                                  
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Phí đỗ xe (mỗi ngày)') ?></td>

                            <td>
                                <?php _e(tpl_input_number('parking_fee', $post['parking_fee'])) ?>                                                                
                                <select name="parking_fee_currency_id" id="" class="bor">
                                    <?php foreach ($currencies as $a): ?>
                                        <option value="<?php _e($a['ID']) ?>" <?php (_e($post['parking_fee_currency_id'] == $a['ID'] ? 'selected' : '')) ?>>
                                            <?php _e($a['title']) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>                                 
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Tiếp tân mở cửa đến') ?></td>

                            <td><?php _e(tpl_input_time('reception_open_until', date('H:i', strtotime($post['reception_open_until'])))); ?></td>
                        </tr>
                        <tr>
                            <td><?php _e('Dịch vụ phòng (Có, Không, 24h)') ?></td>

                            <td>
                                <input type="radio" name='room_service' value="1" <?php _e($post['room_services'] == 1 ? 'checked=checked' : '') ?>">
                                <?php _e('Có') ?>  
                                &nbsp; &nbsp;<input type="radio" name='room_service' value="0" <?php _e($post['room_services'] == 0 ? 'checked=checked' : '') ?>">
                                <?php _e('Không') ?>                                  
                                &nbsp; &nbsp;<input type="radio" name='room_service' value="2" <?php _e($post['room_services'] == 2 ? 'checked=checked' : '') ?>">
                                <?php _e('24 Giờ') ?>  
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Điện áp trong phòng') ?></td>

                            <td><?php _e(tpl_input_number('room_voltage', $post['room_voltage'])) ?></td>
                        </tr>
                        <? /*
                          <tr>
                          <td><?php _e('Thời gian tới sân bay (phút)') ?></td>

                          <td>
                          <?php _e(tpl_input_number('time_airport')) ?>
                          </td>
                          </tr>
                         * 
                         */ ?>
                        <tr>
                            <td><?php _e('Năm xây dựng khách sạn') ?></td>

                            <td>
                                <?php _e(tpl_input_date('year_hotel_built', $post['year_hotel_built'])) ?>                                                        
                            </td>
                        </tr>
                        <tr>
                            <td><?php _e('Năm nâng cấp khách sạn') ?></td>

                            <td>
                                <?php _e(tpl_input_date('year_hotel_last_renovated', $post['year_hotel_last_renovated'])) ?>                                                                                        
                            </td>
                        </tr>
                    </table>
                </div>
            </div>

            <!-- IMAGES -->
            <div class="tab<?php if (get('tab', '') == 'images') _e(' tab-active'); ?>" style="min-height:200px">            
                <div class="x-form-container"> 
                    <?php foreach (self::get('files') as $file) : ?>
                        <div class='x-file-info' style="padding-bottom: 10px;">      
                            
                            <a href="<?php _e(ctrUrl($this)); ?>/File?ID=<?php _e($file['ID']); ?>" target="_blank">                                
                                <img src="<?php _e(BASE_URL) ?>/files/hotel/<?php _e($file['name']) ?>" style="padding:1px;border:1px solid #bbb;max-width:260px"><br/>
                                <input checked type='checkbox' name='files[]' value='<?php _e($file['ID']); ?>'/>
                                <?php _e($file['file_name']); ?> --- <?php _e($file['size']); ?> KB	
                            </a>                        
                            
                        </div>
                    <?php endforeach; ?>	                    

                    <div class="x-files" url="<?php _e(baseUrl()); ?>/Hotel/Index/Upload?ID=<?php _e($post['ID']); ?>"></div>                                        
                </div>
            </div>          


        </div>

        <?php _e(tpl_button_add()) ?>
        <?php _e(tpl_button_cancel('#Hotel')) ?>

    </div>
</form>


<?php
(empty($post['lat'])) ? $lat = 21.012226 : $lat = $post['lat'];
(empty($post['lng'])) ? $lng = 105.847861 : $lng = $post['lng'];
?>
<script type="text/javascript">
    jQuery(document).ready(function(){
        //google map
        var lat = "<?php _e($lat) ?>";
        var lng = "<?php _e($lng) ?>";
        load_google_map(lat,lng);
        jQuery('input[name="refresh_toado"]').click(function(){
            load_google_map(lat,lng);
        })
        
//        //activities check all
//        var activities_checkall =  jQuery('input[name="activities_checkall"]');
//        activities_checkall.click(function(){
//            if(jQuery(this).is(':checked')){
//                jQuery('input[name="activities[]"]').attr('checked',true);
//            }else{
//                jQuery('input[name="activities[]"]').attr('checked',false);
//            }
//        })
    });
   
</script>