<div class="x-list-title">
    <table width="100%" border="0" height="100%">
        <tr>
            <td align="left"><h2><?php _e(translate('default.admin.hotel.order')) ?></h2></td>
            <td align="right">
                <?php
                _e(tpl_search_form(baseUrl() . '/Hotel/Order/Index?s=' . self::get('s'), null, 'Tiêu đề'));
                ?>
                <a href="#Hotel/Order/Add" class="x-button x-button-add"><?php _e(translate('default.add')) ?></a>
            </td>
        </tr>
    </table>
</div>
<?php
list($posts, $vars, $page) = self::get(array('posts', 'vars', 'page'));
$link = '#Hotel/Order/Index';
$id = getId();
?>
<form  id="<?php _e($id); ?>" method="post"  onsubmit="return ajax_form(this)" > 
    <table cellpadding="0" class="x-list" width="100%">
        <?php if (isset($posts) && count($posts) > 0): ?>
            <tr>
                <th class="k"><?php _e(translate('default.list.index')) ?></th>

                <th witdth="30%"> 
                    <?php show_order_link(translate('Mã đơn đặt phòng'), 'root_id', $link, $vars); ?>
                </th>

                <th> 
                    <?php show_order_link(translate('default.hotel.field.room_types'), 'room_title', $link, $vars); ?>
                </th>
                <th> 
                    <?php show_order_link(translate('default.hotel.field.number'), 'amount', $link, $vars); ?>
                </th>

                <th> 
                    <?php show_order_link(translate('default.hotel.field.date_start'), 'date_start', $link, $vars); ?>
                </th>

                <th> 
                    <?php show_order_link(translate('default.hotel.field.date_end'), 'date_end', $link, $vars); ?>
                </th>

                <th> 
                    <?php show_order_link(translate('default.hotel.field.order.fullname'), 'customer_name', $link, $vars); ?>
                </th>
                <th> 
                    <?php show_order_link(translate('default.is_active'), 'status', $link, $vars); ?>
                </th>

                <th colspan="2" witdh="25"><?php _e(translate('default.list.action')); ?></th>

                <th class="k">
            <div class="x-check-container">                
                <div class="x-check">
                    <input rows="tr" type="checkbox" class="x-checkbox"/>
                </div>
                <div class="x-check-options">
                    <div class="s"><span><?php _e(translate('default.action.check')) ?></span></div>
                    <a class="x-check-item" rows="tr">
                        <?php _e(translate('default.action.check_all')) ?>
                    </a>                
                    <div class="x-check-actions">
                        <div class="s"><span><?php _e(translate('default.action.dones')) ?></span></div>
                        <a onclick="module_delete('<?php _e(baseUrl()); ?>/<?php _e(self::getModule()) ?>/<?php _e(self::getController()) ?>/Delete','<?php _e($id); ?>',this)" class="x-check-action">
                            <?php _e(translate('default.action.remove')) ?>
                        </a>
                       <!-- <a onclick="module_ajax('<?php _e(baseUrl()); ?>/<?php _e(self::getModule()) ?>/<?php _e(self::getController()) ?>/Accept','<?php _e($id); ?>',this)" class="x-check-action">
                            <?php _e(translate('default.action.active')) ?>
                        </a>

                        <a onclick="module_ajax('<?php _e(baseUrl()); ?>/<?php _e(self::getModule()) ?>/<?php _e(self::getController()) ?>/Cancel','<?php _e($id); ?>',this)" class="x-check-action">
                            <?php _e(translate('default.action.order.cancel')) ?>
                        </a>
                       -->
                    </div>
                </div>
            </div>
            </th>
            </tr>
            <?php foreach ($posts as $k => $a): ?>
                <tr>
                    <td align="center"><?php _e($k + 1) ?> </td> 
                    <td witdth="30%">
                        <a href="#Hotel/Order/View?ID=<?php _e($a['ID']) ?>">
                            <span style="color:red;font-weight: bold">HD-<?php _e($a['root_id']) ?></span>
                        </a>
                    </td>
                    <td witdth="30%"> 
                        <a href="#Hotel/Room/View?ID=<?php _e($a['room_id']) ?>">
                            <?php _e($a['room_title']) ?>
                        </a>
                    </td>
                    <td align="center"> <?php _e($a['amount']) ?></td>
                    <td align="center"> <?php _e(show_date('d/m/Y', $a['date_start'])) ?></td>
                    <td align="center"> <?php _e(show_date('d/m/Y', $a['date_end'])) ?></td>
                    <td align="center"> <?php _e($a['customer_name']); ?></td>

                    <td align="center">
                        <?php
                        if ($a['status'] == 0) { 
                            $title_status = 'default.order.wait_accept';
                        } elseif ($a['status'] == 1) {
                             $title_status = 'Xác nhận';
                        } elseif ($a['status'] == 2) {
                              $title_status = 'default.order.no_accept';
                        } elseif ($a['status'] == 3) {
                              $title_status = 'Chờ xác nhận sửa';
                        };
                        
                        ?>
                         <a href="<?php _e(append_url("#Hotel/Order/Index?status={$a['status']}", $vars)); ?>">
                            <?php _e(translate($title_status)) ?>
                        </a>
                    </td>
                    <td width='30' align='center'>
                        <?php if($a['status'] == 0 || $a['status'] == 1 || $a['status'] == 3 ):?>
                            <a href="#Hotel/Order/Edit?ID=<?php _e($a['ID']) ?>" class="x-edit"></a>
                        <?php else:?>
                            <a class="x-noedit"></a>
                        <?php endif;?>
                    </td>
                    <td class="k" align='center'>
                        <?php if($a['status'] == 2) : ?>
                        <a onclick='module_delete("<?php _e(baseUrl()); ?>/Hotel/Order/Delete?ID[]=<?php _e($a['ID']); ?>")' class='x-delete'></a>
                        <?php else: ?>
                            <a class="x-nodelete"></a>
                        <?php endif;?>
                    </td>

                    <td align="center">
                        <input name="ID[]" value="<?php _e($a['ID']) ?>" type="checkbox"/>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        <tr>
            <td colspan="12" class="page">
                <div class="x-page">
                    <?php self::e("page"); ?>
                </div>
            </td>
        </tr>
    </table>

</form>

