<?php
$post = self::get('post');
?>
<div class="x-list-title">
    <table width="100%" border="0" height="100%">
        <tr>
            <td align="left"><h2><?php _e('Xem thông tin phụ phí') ?></h2>
            </td>
            <td align="right">
                <div class="x-list-options">
                    <a href="#Hotel/Surcharge/Edit?ID=<?php _e($post['ID']) ?>" class="x-button" >
                         Chỉnh Sửa
                    </a>
                    <?php _e(tpl_button_cancel('#Hotel/Surcharge')) ?>   
                </div>
            </td>
        </tr>
    </table>
</div>

<div class="x-form-container">
    <table width="100%" cellpadding="4" class="x-form">
        <tr>
            <td class="x-form-label"><?php _e('Tên phụ phí' . ':') ?></td>
            <td class="x-form-content">
                <?php _e($post['surcharge_title']) ?>
            </td>
        </tr>

        <tr>
            <td class="c1">Ngày bắt đầu</td>
            <td class="c2">
                <?php _e(date('d/m/Y',strtotime($post['date_start']))); ?>
            </td> 
        </tr>
        <tr>
            <td class="x-form-label">Ngày kết thúc</td>
            <td class="x-form-content">
                <?php _e(date('d/m/Y',strtotime($post['date_end']))); ?>
            </td>
        </tr>            
        <tr>
            <td class="x-form-label">
                <?php _e(translate('default.hotel.field.days')) ?>:
            </td>
            <td class="x-form-content" nowrap="nowrap">
                <?php
                $n = explode(',', $post['days']);
                ?>
                <?php for ($i = 1; $i < 7; $i++): ?>
                    <input name="days[]" type="checkbox" value="<?php _e($i % 7) ?>"<?php _e(in_array($i, $n) ? ' checked' : '' ) ?>  disabled/>
                    <?php _e(translate('default.work.day' . ($i))) ?>&nbsp;&nbsp;&nbsp;&nbsp;
                <?php endfor; ?>
                <input name="days[]" type="checkbox" value="0"<?php _e(in_array(0, $n) ? ' checked' : '' ) ?> disabled />
                <?php _e(translate('default.work.day' . (0))) ?>&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
        </tr>          

        <tr>
            <td class="x-form-label"><?php _e('Số tiền') ?></td>
            <td class="x-form-content">                    
                <?php _e($post['money'] . ' ' . $post['currency_name']) ?>                                         
            </td>
        </tr>

        <tr>	
            <td class="x-form-label" valign="top"><?php _e(translate('default.desc') . ':') ?></td>
            <td class="x-form-content">                    
                <?php _e($post['desc']) ?>
            </td>
        </tr>        
    </table>
</div>