<?php
$room_types = self::get('room_types');
?>

<div class="x-list-title">
    <table width="100%" border="0" height="100%">
        <tr>
            <td align="left">
                <h2>Thêm mới phụ phí</h2>
            </td>
            <td align="right">
                <div class="x-list-options">

                </div>
            </td>
        </tr>
    </table>
</div>
<form method="post" action="<?php _e(actionUrl()) ?>" onsubmit="return ajax_form(this)">
    <div class="x-form-container" style="overflow: true;">
        <div class="form-message"></div>
        <table width="100%" border="0" cellpadding="5" class="x-form">    
            <tr>
                <td class="x-form-label"><?php _e('Tên phụ phí ' . ':') ?></td>
                <td class="x-form-content">
                    <?php _e(tpl_select('surcharge_id', 'ID', 'title', self::get('surcharge_types'), null, true)) ?>
                </td>
            </tr>

            <tr>
                <td class="c1">Ngày bắt đầu</td>
                <td class="c2">
                    <?php _e(tpl_input_date('date_start')); ?>
                </td> 
            </tr>
            <tr>
                <td class="x-form-label">Ngày kết thúc</td>
                <td class="x-form-content">
                    <?php _e(tpl_input_date('date_end')); ?>
                </td>
            </tr>

            <tr>
                <td class="x-form-label">
                    <?php _e(translate('default.hotel.field.days')) ?>:
                </td>
                <td class="x-form-content" nowrap="nowrap">
                    <?php
                    $n = array('0', '1', '2', '3', '4', '5', '6', '7');
                    ?>
                    <?php for ($i = 1; $i < 7; $i++): ?>
                        <input name="days[]" type="checkbox" value="<?php _e($i % 7) ?>"<?php _e(in_array($i, $n) ? ' checked' : '' ) ?> />
                        <?php _e(translate('default.work.day' . ($i))) ?>&nbsp;&nbsp;&nbsp;&nbsp;
                    <?php endfor; ?>
                    <input name="days[]" type="checkbox" value="0"<?php _e(in_array(0, $n) ? ' checked' : '' ) ?> />
                    <?php _e(translate('default.work.day' . (0))) ?>&nbsp;&nbsp;&nbsp;&nbsp;
                    <?php
                    ?>
                </td>
            </tr>           

            <tr>
                <td class="x-form-label"><?php _e('Số tiền') ?></td>
                <td class="x-form-content">                    
                    <?php _e(tpl_input_number('money')) ?>                                
                    <?php _e(tpl_select('currency', 'ID', 'title', self::get('currencies'), null, true)) ?>                                                
                </td>
            </tr>

            <tr>	
                <td class="x-form-label" valign="top"><?php _e(translate('default.desc') . ':') ?></td>
                <td class="x-form-content">
                    <textarea name="desc" style="width:250px" class="x-text" rows="6"></textarea>
                </td>
            </tr>        
            <tr>
                <td align="center" colspan="2">
                    <?php _e(tpl_button_add()) ?>
                    <?php _e(tpl_button_cancel("#Hotel/Surcharge")) ?>
                </td>
            </tr>
        </table>
    </div>
</form>
