<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<table width="100%" height="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td class="side" valign="top"><div id="side">
                <!--LINK TAC VU-->
                <ul class="links">
                    <li class="big-link"><a>Cấu hình</a></li>
                    <li class="sub-big-link">
                        <div><a>Tổng quát</a></div>
                    </li>
                    <!--
                    <li class="sub-link<?php if ( self::getControllerName() == 'AdminStatsController' ) _e(' sub-link-current'); ?>"><a href="#Admin/Stats">Thống kê</a></li>
                    -->
                    <li class="sub-link<?php if ( self::getControllerName() == 'AdminLayoutController' ) _e(' sub-link-current'); ?>"><a href="#Admin/Layout">Cấu hình chung</a></li>
                    <li class="sub-link<?php if ( self::getControllerName() == 'AdminSmsController' ) _e(' sub-link-current'); ?>"><a href="#Admin/SMS">Thống kê tin SMS</a></li>
                    <li class="sub-link<?php if ( self::getControllerName() == 'AdminLanguageController' ) _e(' sub-link-current'); ?>">
                        <a href="#Admin/Language">Ngôn ngữ</a></li>
                    <li class="sub-link<?php if ( self::getControllerName() == 'AdminFaqController' ) _e(' sub-link-current'); ?>">
                        <a href="#Admin/Faq">Soạn thảo FAQ</a></li>
                    <li class="sub-link<?php if ( self::getControllerName() == 'AdminOptermizeController' ) _e(' sub-link-current'); ?>"><a href="#Admin/Log">Nhật ký truy cập</a></li>
                    <li class="sub-link sub-link-last<?php if ( self::getControllerName() == 'AdminOptermizeController' ) _e(' sub-link-current'); ?>"><a href="#Admin/Optermize">Tối ưu hóa bộ nhớ</a></li>

			<li class="sub-big-link">
				<div><a>Người dùng</a></div>
			</li>
			<li class="sub-link<?php if(self::getControllerName() =='AdminUserController' && self::getAction() == 'index' )  _e(' sub-link-current');?>"><a href="#Admin/User">Người dùng</a></li>
			<li class="sub-link sub-link-last <?php if(self::getController() =='Group')  _e(' sub-link-current');?>"><a href="#Admin/Group">Nhóm người dùng</a></li>

			
                        <li class="sub-big-link">
				<div><a>Khách sạn</a></div>
			</li>   
                        <li class="sub-link<?php if(self::getControllerName() =='AdminHotelsController')  _e(' sub-link-current');?>"><a href="#Admin/Hotels">Danh sách khách sạn</a></li>
                        
                        <li class="sub-link<?php if(self::getControllerName() =='AdminHotelActivitiesController')  _e(' sub-link-current');?>"><a href="#Admin/HotelActivities">Tiện ích giải trí</a></li>
                        <li class="sub-link<?php if(self::getControllerName() =='AdminHotelFacilitiesController')  _e(' sub-link-current');?>"><a href="#Admin/HotelFacilities">Chức năng</a></li>
                        <li class="sub-link<?php if(self::getControllerName() =='AdminHotelServicesController')  _e(' sub-link-current');?>"><a href="#Admin/HotelServices">Dịch vụ</a></li>
                        <li class="sub-link<?php if(self::getControllerName() =='AdminHotelTypesController')  _e(' sub-link-current');?>"><a href="#Admin/HotelTypes">Loại khách sạn</a></li>
                        
                         <li class="sub-big-link">
				<div><a>Loại phòng</a></div>
			</li>                        
                        <li class="sub-link<?php if(self::getControllerName() =='AdminRoomServicesController')  _e(' sub-link-current');?>"><a href="#Admin/RoomServices">Dịch vụ phòng</a></li>
                        <li class="sub-link<?php if(self::getControllerName() =='AdminOrderTypesController')  _e(' sub-link-current');?>"><a href="#Admin/OrderTypes">Hình thức đặt phòng</a></li>
                        
                        
            </li>
		</ul>
	</div></td>
	<td class="content" valign="top">
		<div id="content">
			<?php self::showContent(); ?>
		</div>
	</td>
</tr>
</table>
