<?php
$hotel_id = get_hotel_id();
$room_type = self::$Model->fetchAll(
        "SELECT * 
                FROM `hotel_room_types` as `a`
                WHERE `a`.`hotel_id` = '{$hotel_id}' 
                ORDER BY `a`.`ID` ASC
                ");
if (!empty($room_type)) {
    $room_type_id_first = $room_type[0]['ID'];
}
?>
<table width="100%" height="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td class="side" valign="top">
            <div id="side">
                <?php
                $hotel = get_hotel();
                ?>
                    <ul class="links">
                        <li class="big-link"><a>Cấu hình</a></li>
                        <li class="sub-big-link">
                            <div><a>Tổng quát</a></div>
                        </li>
                        <?php _e(tpl_menu_side(array(
                            array(
                                title => 'Quản lý đối tác',
                                url => '#Config/Partners'
                            )
                        ))) ?>
                    </ul>
                    
            </div>
        </td>
        <td class="content" valign="top">
            <div id="content">
                <?php self::showContent(); ?>
            </div>
        </td>
    </tr>
</table>
